spring.application.name=job-tracker-backend
spring.data.mongodb.uri=mongodb+srv://kartiksharma:kartik%401@cluster0.nlrknbv.mongodb.net/test
server.port=${PORT:8080}
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
